export const REQUEST_POSTS = 'REQUEST_POSTS'
export const REQUEST_POSTS_RESOLVED = 'REQUEST_POSTS_RESOLVED'
export const REQUEST_POSTS_REJECTED = 'REQUEST_POSTS_REJECTED'

export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT'
export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT'
